services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ENV=development
      - TRANSACTIONS_DB_DSN=postgres://transactions:${DB_PASSWORD}@db/transactions?sslmode=disable
    command: ["./transaction-processor"]
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/v1/livez"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=transactions
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=transactions
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transactions"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://transactions:${DB_PASSWORD}@db:5432/transactions?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: